# Generated by Django 2.0.5 on 2018-06-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_auto_20180517_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_app.Profile'),
        ),
    ]
