# Generated by Django 2.0.5 on 2018-07-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_auto_20180702_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='access_token',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='bank',
            name='item_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
