# Generated by Django 2.0.5 on 2018-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_auto_20180705_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='item_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
