# Generated by Django 2.0.7 on 2018-07-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_auto_20180705_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='access_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
    ]
