# Generated by Django 2.0.7 on 2018-07-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0010_ask_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
