# Generated by Django 2.0.7 on 2018-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0013_auto_20180709_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
