# Generated by Django 2.0.7 on 2018-08-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0014_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwolla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('plaid_token', models.CharField(blank=True, max_length=100)),
                ('account_url', models.CharField(blank=True, max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock_app.Profile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
